name: Lint Python

on:
  pull_request:

jobs:
  docker_lint:
    name: Lint Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.x"
      - name: Set up Poetry and upgrade pip
        run: |
          pip install -U pip poetry
      - name: Install flows
        run: |
          pip install --prefer-binary .
      - name: Install pylint
        run: pip install pylint
      - name: Lint flows
        run: pylint pipelines/*
      - name: Install Pytest
        run: pip install pytest
      - name: Lint tests
        run: pylint tests/*
